"""Checked current-document item observation; never activates the authoring DB."""
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import tempfile

from src.checklist_item_master import export_item_master
from src.item_review import observe_item_master
from src.review_service import DEFAULT_MAPPING, validate_extraction_environment
from src.xml_review_gate import ARTIFACT_NAMES

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ITEM_MASTER = ROOT / 'metadata/checklist_v2/item_master_drafts/20260911'
EXPECTED_SEED_SHA256 = '2229a46be82d9f7b3a6aa316c079eea93f15481050d2e44020c850ddfc73e268'
MASTER_NAMES = ('checklist_item_master.json', 'checklist_item_master.xlsx', 'master_seed.json')


def _require(condition, message):
    if not condition:
        raise ValueError(message)


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        _require(key not in result, f'duplicate JSON key: {key}')
        result[key] = value
    return result


def _canonical(value):
    return json.dumps(value, ensure_ascii=True, sort_keys=True, allow_nan=False)


def load_checked_item_master(master_dir: Path = DEFAULT_ITEM_MASTER) -> dict:
    """Reproduce the complete Excel export against an independently pinned seed.

    The stored JSON is accepted only on full equality, including source evidence,
    provenance and author proposals. No active runtime DB is produced here.
    """
    folder = Path(master_dir)
    before = {folder / name: (folder / name).read_bytes() for name in MASTER_NAMES}
    with tempfile.TemporaryDirectory(prefix='checked-item-master-') as scratch:
        reproduced = export_item_master(folder / MASTER_NAMES[1], folder / MASTER_NAMES[2],
                                       Path(scratch) / 'reproduced.json', expected_seed_sha256=EXPECTED_SEED_SHA256)
    stored = json.loads(before[folder / MASTER_NAMES[0]], object_pairs_hook=_unique_object)
    _require(_canonical(stored) == _canonical(reproduced), 'stored item JSON differs from checked Excel export')
    _require(all(path.read_bytes() == content for path, content in before.items()), 'master input changed during validation')
    return reproduced


def _json_text(value):
    return json.dumps(value, ensure_ascii=True, indent=2) + '\n'


def _digest(content):
    return hashlib.sha256(content).hexdigest()


def _write_new(path, text):
    with Path(path).open('x', encoding='utf-8', newline='\n') as stream:
        stream.write(text)
        stream.flush()
        os.fsync(stream.fileno())


def _unchanged(snapshot):
    for path, content in snapshot.items():
        _require(path.is_file() and path.read_bytes() == content, f'input or output changed: {path.name}')


@dataclass(frozen=True)
class ItemReviewRequest:
    pdf: Path
    output_dir: Path
    bundle: Path | None = None
    mapping: Path = DEFAULT_MAPPING
    master_dir: Path = DEFAULT_ITEM_MASTER


def run_item_review(request: ItemReviewRequest) -> dict:
    """Publish a new draft observation and HTML, with a completion record last.

    Every consumed file and generated byte is checked again around publication.
    Failure records invalidate even a receipt whose final link just succeeded.
    """
    output = Path(request.output_dir)
    output.mkdir(parents=True, exist_ok=False)
    published = False
    try:
        from src.item_review_report import render_item_review_html
        from src.semantic_xml_reader import read_review_bundle
        pdf, mapping, master_dir = Path(request.pdf), Path(request.mapping), Path(request.master_dir)
        paths = (pdf, mapping, *(master_dir / name for name in MASTER_NAMES))
        inputs_before = {path: path.read_bytes() for path in paths}
        master = load_checked_item_master(master_dir)
        bundle = Path(request.bundle) if request.bundle is not None else output / 'extraction'
        if request.bundle is None:
            validate_extraction_environment()
            from src.xml_review_run import extract_review_document
            extract_review_document(pdf, bundle, mapping)
        receipt_path = bundle / 'review_run.json'
        receipt_bytes = receipt_path.read_bytes()
        receipt = json.loads(receipt_bytes)
        inputs_before[receipt_path] = receipt_bytes
        for name in ARTIFACT_NAMES:
            inputs_before[bundle / name] = (bundle / name).read_bytes()
        if 'review_document_sha256' in receipt:
            path = bundle / 'review_document.json'
            inputs_before[path] = path.read_bytes()
            _require(_digest(inputs_before[path]) == receipt['review_document_sha256'], 'review document hash differs')
        document = read_review_bundle(bundle, receipt, pdf_path=pdf, mapping_path=mapping)
        _unchanged(inputs_before)
        report = observe_item_master(document, master)
        report['target_source'] = {
            'pdf_filename': pdf.name, 'pdf_sha256': _digest(inputs_before[pdf]),
            'semantic_xml_sha256': _digest(inputs_before[bundle / 'semantic_document.xml']),
            'receipt_ref': str(receipt_path.resolve()), 'receipt_sha256': _digest(receipt_bytes),
            'bundle_path': str(bundle.resolve()),
        }
        named = dict(zip(('pdf', 'mapping', 'master_json', 'master_excel', 'master_seed'), paths, strict=True))
        named['receipt'] = receipt_path
        report['inputs'] = {k: v for key, path in named.items()
                            for k, v in ((key, str(path.resolve())), (key + '_sha256', _digest(inputs_before[path])))}
        report['inputs']['source_bundle'] = receipt
        json_text = _json_text(report)
        _write_new(output / 'item_observation.json', json_text)
        html = render_item_review_html(report)
        _require(_json_text(report) == json_text, 'item observation changed during rendering')
        _validate_report(report)
        expected = {output / 'item_observation.json': json_text.encode('utf-8'),
                    output / 'item_review.html': html.encode('utf-8')}
        _write_new(output / 'item_review.html', html)
        completion = {'schema_version': 'checklist-item-observation-run/1', 'status': 'ready_for_human_review',
                      'decision_status': 'not_evaluated', 'activation_status': 'draft_only',
                      'summary': report['summary'],
                      'artifacts': {path.name: _digest(content) for path, content in expected.items()}}
        def verify():
            _require(not (output / 'item_review_failed.json').exists(), 'failed run cannot complete')
            _unchanged(inputs_before)
            _unchanged(expected)
        verify()
        pending = output / 'item_review_complete.pending.json'
        completion_text = _json_text(completion)
        _write_new(pending, completion_text)
        expected[pending] = completion_text.encode('utf-8')
        verify()
        final = output / 'item_review_complete.json'
        os.link(pending, final)
        published = True
        expected[final] = expected[pending]
        verify()
        try:
            pending.unlink()
        except OSError:
            pass
        return completion
    except Exception as exc:
        if published:
            try:
                (output / 'item_review_complete.json').unlink()
            except OSError:
                pass  # The failure marker below also invalidates a published receipt.
        try:
            _write_new(output / 'item_review_failed.json', _json_text({
                'status': 'failed', 'decision_status': 'not_evaluated', 'activation_status': 'draft_only',
                'error_type': type(exc).__name__, 'reason': str(exc)}))
        except OSError:
            pass
        raise


def _validate_report(report):
    _require(report.get('schema_version') == 'checklist-item-observation/1'
             and report.get('decision_status') == 'not_evaluated'
             and report.get('activation_status') == 'draft_only', 'invalid item observation schema or state')
    items = report['items']
    _require(len(items) == 14 and len({i['item_key'] for i in items}) == 14
             and report['parent_check_id'] == 'CHK-002-ZC-ENG', 'invalid or duplicate completed items')
    states = ('found', 'ambiguous', 'not_found', 'not_examined')
    for item in items:
        _require(item['result'] == 'needs_review' and item['model_applicability'] == 'unknown'
                 and item['condition_state'] == 'unverified' and item['observation'] in states,
                 'invalid completed item decision')
        count = len(item['candidates'])
        _require((item['observation'] == 'found' and count == 1)
                 or (item['observation'] == 'ambiguous' and count > 1)
                 or (item['observation'] in ('not_found', 'not_examined') and count == 0),
                 'item observation differs from candidate count')
    summary = {'item_count': 14, 'needs_review': 14,
               **{state: sum(i['observation'] == state for i in items) for state in states},
               'condition_candidate_items': sum(bool(i['condition_candidates']) for i in items)}
    _require(report['summary'] == summary, 'item summary differs from completed rows')


def read_completed_item_review(output: Path) -> dict:
    """Read an archival snapshot, checking outputs without requiring live inputs.

    Recorded hashes detect accidental changes; they are not approval signatures.
    """
    output = Path(output)
    failure = output / 'item_review_failed.json'
    _require(not failure.exists(), 'failed run cannot be consumed')
    path = output / 'item_review_complete.json'
    snapshot = {path: path.read_bytes()}
    receipt = json.loads(snapshot[path])
    _require(receipt.get('schema_version') == 'checklist-item-observation-run/1'
             and receipt.get('status') == 'ready_for_human_review'
             and receipt.get('decision_status') == 'not_evaluated'
             and receipt.get('activation_status') == 'draft_only', 'invalid item completion receipt')
    _require(set(receipt.get('artifacts', {})) == {'item_observation.json', 'item_review.html'},
             'unexpected completed artifacts')
    for name, digest in receipt['artifacts'].items():
        artifact = output / name
        snapshot[artifact] = artifact.read_bytes()
        _require(_digest(snapshot[artifact]) == digest, f'completed artifact changed: {name}')
    report = json.loads(snapshot[output / 'item_observation.json'])
    _validate_report(report)
    _require(report['summary'] == receipt.get('summary'), 'observation and completion summary differ')
    _unchanged(snapshot)
    _require(not failure.exists(), 'failed run cannot be consumed')
    return report
